modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="telepastries"
version="${file.jarVersion}"
displayName="TelePastries"
displayURL="https://github.com/Mrbysco/TelePastries"
authors="Mrbysco"
description='''Pastries that teleport players.'''
credits="My friend 8138763 for the name"

[[dependencies.telepastries]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"